syntax

diff --git a/.github/workflows/branch.yml b/.github/workflows/branch.yml
--- a/.github/workflows/branch.yml
+++ b/.github/workflows/branch.yml
@@ -22,6 +22,7 @@ jobs:
               git config --global --add safe.directory $PWD
           # ref.: https://github.com/actions/checkout, v3.0.0
           # SOURCE_ORIGIN=${SOURCE_ORIGIN#"origin/"} && SOURCE_ORIGIN=${SOURCE_ORIGIN#"refs/heads/"}
+          # git log --cherry-pick --left-right e6797a76359104f56ce0a3656a97d3f1242881b9 ^remote/branchname
           - name: Checkout repository
             uses: actions/checkout@a12a3943b4bdde767164f792f33f40b04645d846
           - name: Extract branch name on pull request
@@ -42,8 +43,11 @@ jobs:
               echo "LATEST_REF=$(git ls-remote https://github.com/kiracore/$REPOSITORY_NAME latest | awk '{ print $1}')" >> $GITHUB_ENV
               echo "SOURCE_REF=$(echo $GITHUB_SHA)" >> $GITHUB_ENV
 
+              git gc
+              git fetch origin
               git branch -r --contains $SOURCE_BRANCH~1 || echo "WARNING: Failed to find '$SOURCE_BRANCH' origin 1"
               git branch -r --contains origin/$SOURCE_BRANCH~1 || echo "WARNING: Failed to find '$SOURCE_BRANCH' origin 2"
+              git branch -r --contains remotes/origin/$SOURCE_BRANCH~1 || echo "WARNING: Failed to find '$SOURCE_BRANCH' origin 2.5"
               git branch -r --contains refs/heads/$SOURCE_BRANCH~1 || echo "WARNING: Failed to find '$SOURCE_BRANCH' origin 3"
 
               git ls-remote https://github.com/kiracore/$REPOSITORY_NAME
@@ -51,6 +55,8 @@ jobs:
               SOURCE_ORIGIN=$(git branch -r --contains $SOURCE_BRANCH~1  | sed -n -e '2{p;q}' | tr -d '\011\012\013\014\015\040' || echo "")
               [ -z "$SOURCE_ORIGIN" ] && \
                 SOURCE_ORIGIN=$(git branch -r --contains origin/$SOURCE_BRANCH~1  | sed -n -e '2{p;q}' | tr -d '\011\012\013\014\015\040' || echo "")
+              [ -z "$SOURCE_ORIGIN" ] && \
+                SOURCE_ORIGIN=$(git branch -r --contains remotes/origin/$SOURCE_BRANCH~1  | sed -n -e '2{p;q}' | tr -d '\011\012\013\014\015\040' || echo "")
               [ -z "$SOURCE_ORIGIN" ] && \
                 SOURCE_ORIGIN=$(git branch -r --contains refs/heads/$SOURCE_BRANCH~1  | sed -n -e '2{p;q}' | tr -d '\011\012\013\014\015\040' || echo "")
 
