Immediately stop the loop if file is pinned or found

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -111,13 +111,14 @@ jobs:
               IPFS_HASH=""
               IPFS_UPLOAD_NAME=kira-$RELEASE_VER
               CHECK_ELAPSED=0
-              while [ -z "$IPFS_HASH" ] || [[ $CHECK_ELAPSED -gt 900 ]] ; do
+              while [[ $CHECK_ELAPSED -lt 900 ]] ; do
                 bash-utils echoInfo "INFO: Waiting for IPFS files to be pinned, timeout in ${CHECK_ELAPSED}/900s..."
                 rm ./ipfs-pinned.log && touch ./ipfs-pinned.log
                 sleep 10
-                ipfs-api pinned $IPFS_UPLOAD_NAME --key=${{secrets.PINATA_API_JWT}} --verbose=true | tee -a ./ipfs-pinned.log || echo "ERROR: Faile to find pinned files"
+                ipfs-api pinned $IPFS_UPLOAD_NAME --key=${{secrets.PINATA_API_JWT}} --verbose=true | tee -a ./ipfs-pinned.log || echo "ERROR: Failed to find pinned files"
                 IPFS_HASH=$(cat ./ipfs-pinned.log | tail -n 1 | bash-utils jsonParse "rows.[0].ipfs_pin_hash" || echo "")
                 cat ./ipfs-pinned.log
+                [ ! -z "$IPFS_HASH" ] && break 
                 sleep 10
                 CHECK_ELAPSED=$(bash-utils timerSpan "pinned-timeout")
               done
@@ -133,13 +134,14 @@ jobs:
               IPFS_HASH=""
               IPFS_UPLOAD_NAME=kira-$RELEASE_VER
               CHECK_ELAPSED=0
-              while [ -z "$IPFS_HASH" ] || [[ $CHECK_ELAPSED -gt 300 ]] ; do
+              while [[ $CHECK_ELAPSED -lt 300 ]] ; do
                 bash-utils echoInfo "INFO: Attempting fils pin to IPFS, timeout in ${CHECK_ELAPSED}/900s..."
                 rm ./ipfs-pin.log && touch ./ipfs-pin.log
                 ipfs-api delete $IPFS_UPLOAD_NAME --key=${{secrets.PINATA_API_JWT}} --verbose=true || echo "WARNING: Failed to delete file with name '$IPFS_UPLOAD_NAME' request failed or it might not exist"
                 ipfs-api pin ./bin/ipfs $IPFS_UPLOAD_NAME --key=${{secrets.PINATA_API_JWT}} --verbose=true | tee -a ./ipfs-pin.log || echo "ERROR: Failed to pin web app"
                 IPFS_HASH=$(cat ./ipfs-pin.log | tail -n 1 | bash-utils jsonParse ".hash" || echo "")
                 cat ./ipfs-pin.log || echo "ERROR: Failed to print error logs"
+                [ ! -z "$IPFS_HASH" ] && break 
                 sleep 10
                 CHECK_ELAPSED=$(bash-utils timerSpan "pin-timeout")
               done
