use force flag when pinning files

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -92,12 +92,13 @@ jobs:
             run: |
               set -x
               make publish
-              mkdir -p ./bin/ipfs
-              cp -fv ./bin/kira.zip ./bin/ipfs
-              cp -fv ./bin/init.sh ./bin/ipfs
+              IPFS_UPLOAD_NAME=kira-$RELEASE_VER
+              mkdir -p ./bin/$IPFS_UPLOAD_NAME
+              cp -fv ./bin/kira.zip ./bin/$IPFS_UPLOAD_NAME
+              cp -fv ./bin/init.sh ./bin/$IPFS_UPLOAD_NAME
               echo "$KEY" > ../cosign.key
-              cosign sign-blob --key=../cosign.key --output-signature=./bin/ipfs/init.sh.sig ./bin/ipfs/init.sh || ( rm -fv ../cosign.key && exit 1 )
-              cosign sign-blob --key=../cosign.key --output-signature=./bin/ipfs/kira.zip.sig ./bin/ipfs/kira.zip || ( rm -fv ../cosign.key && exit 1 )
+              cosign sign-blob --key=../cosign.key --output-signature=./bin/$IPFS_UPLOAD_NAME/init.sh.sig ./bin/$IPFS_UPLOAD_NAME/init.sh || ( rm -fv ../cosign.key && exit 1 )
+              cosign sign-blob --key=../cosign.key --output-signature=./bin/$IPFS_UPLOAD_NAME/kira.zip.sig ./bin/$IPFS_UPLOAD_NAME/kira.zip || ( rm -fv ../cosign.key && exit 1 )
               rm -fv ../cosign.key 
           - name: Find or await IPFS files to be pinned
             if: github.event_name == 'pull_request' || 
@@ -142,13 +143,11 @@ jobs:
                 IPFS_HASH=$(cat ./ipfs-pinned.log | tail -n 1 | bu jsonParse "rows.[0].ipfs_pin_hash" || echo "")
                 cat ./ipfs-pinned.log || bu echoErr "ERROR: Failed to print pin check error logs"
 
-                if [ ! -z "$IPFS_HASH" ] ; then
-                  ipfs-api delete $IPFS_HASH --key=${{secrets.PINATA_API_JWT}} --verbose=true || bu echoWarn "WARNING: Failed to delete file with hash '$IPFS_HASH' request failed or it might not exist"
-                else
-                  ipfs-api delete $IPFS_UPLOAD_NAME --key=${{secrets.PINATA_API_JWT}} --verbose=true || bu echoWarn "WARNING: Failed to delete file with name '$IPFS_UPLOAD_NAME' request failed or it might not exist"
-                fi
-                
-                ipfs-api pin ./bin/ipfs $IPFS_UPLOAD_NAME --key=${{secrets.PINATA_API_JWT}} --verbose=true | tee -a ./ipfs-pin.log || bu echoErr "ERROR: Failed to pin web app"
+                [ ! -z "$IPFS_HASH" ] && \
+                ipfs-api delete $IPFS_HASH --key=${{secrets.PINATA_API_JWT}} --verbose=true || bu echoWarn "WARNING: Failed to delete file with hash '$IPFS_HASH' request failed or it might not exist"
+                ipfs-api delete $IPFS_UPLOAD_NAME --key=${{secrets.PINATA_API_JWT}} --verbose=true || bu echoWarn "WARNING: Failed to delete file with name '$IPFS_UPLOAD_NAME' request failed or it might not exist"
+
+                ipfs-api pin ./bin/$IPFS_UPLOAD_NAME $IPFS_UPLOAD_NAME --key=${{secrets.PINATA_API_JWT}} --verbose=true --force=true | tee -a ./ipfs-pin.log || bu echoErr "ERROR: Failed to pin web app"
                 IPFS_HASH=$(cat ./ipfs-pin.log | tail -n 1 | bu jsonParse ".hash" || echo "")
                 cat ./ipfs-pin.log || bu echoErr "ERROR: Failed to print pin error logs"
                 [ ! -z "$IPFS_HASH" ] && break 
